### ISSUE TITLE
Array index offset error

### ISSUE THREAD

**Issue by evbauer** [rjfarmer/pyMesa#2]
I'm trying to call the EOS, and I've run into an index offset problem that wasn't around last time I used pyMesa (fall 2017 with version 10000).

As shown in eos.py, one has to subtract 1 from that you get from eos_def to make sure you get the right element of the "res" array. E.g.
`i_lnE = eos_def.i_lnE.get() - 1`
`E = np.exp(res[i_lnE])`
The README mentions this and notes that numpy indexes from 0 while fortran indexes from 1. So far, no big deal.

BUT, with my most recent installation of pyMesa (yesterday), somehow the EOS quantities are shifted even further in the "res" array, so that now I have to subtract 2 to get the right quantity. So the above example has to become
`i_lnE = eos_def.i_lnE.get() - 2`
`E = np.exp(res[i_lnE])`
Even worse, lnPgas should be the first element of the "res" array, but seems to have been shifted out of the array altogether, while the last entry of the array is never filled with anything. So I can't ask the EOS what the pressure is!

Could this be caused by some change in gfort2py? Is there maybe a version of pyMesa and/or gfort2py that I can install to run with 10398 that won't have this bug?

**Comment by evbauer** [comment]
Some other quick notes:
This problem occurred when I cloned and installed the latest version of the repository. I was also using gfort2py v1.1.2

I downgraded to gfort2py v1.0.11 and pyMesa v1.0.3, and the indexing error is gone.

**Comment by rjfarmer** [comment]
You shouldn't need to change the pymesa version, as that is just concerned with getting mesa built with shared library support. But yeah the issue would be in gfort2py as there have been many changes to how the arrays are handled. For now i'd suggest sticking with v1.0.11 if it works and use the most recent pymesa if possible.

The issue the arrays being passed as (:) need an array descriptor created and its a little confusing, unclear, and undocumented what goes on here so i keep ending up with off by one errors for one type of array declared (:) (allocatable, pointer, or just dimension(:). Fix one type and the then the others break.

What i usually do is make a "simple" wrapper function/subroutine in the lib file that accepts only scalars or arrays with a fixed size (i.e dimension(10)) then call the mesa function from there, so that its fortran handling the allocatable/pointer arrays not python. Then you can return scalar/or fixed sized arrays as dummy arguments

**Comment by evbauer** [comment]
Thanks. I managed to do everything I needed with gfort2py v1.0.11. I think I'll go ahead and close this issue since it isn't really a problem with pyMesa. I won't open an issue on gfort2py since I'm not really sure how to describe it. I'll just let you decide how to handle it since you're clearly aware that arrays continue to be tricky.

**Comment by rjfarmer** [comment]
Hi If you have a chance could you try gfort2py version 1d55751, i think i fixed things

**Comment by evbauer** [comment]
Ok, I just tried it out, and it looks fixed for the stuff I was doing.
